config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"

  get "static_pages/home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: %i(index destroy)
  resources :change_date_booking, only: :show
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(new index create)
  
  resources :pitches do
    resources :bookings
  end

  namespace :owner do
    resources :pitches
  end
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  has_many :user_pitch_reactions, class_name: UserPitchReaction.name
  has_many :bookings, through: :user_pitch_reactions, source: :reactions,
    source_type: Booking.name, dependent: :destroy
  has_many :comments, through: :user_pitch_reactions, source: :reactions,
    source_type: Comment.name, dependent: :destroy

  scope :create_at_desc, -> {order created_at: :desc}
  scope :search_pitch, ->search{where("description LIKE ?", "%#{search}%").or where("address LIKE ?","%#{search}%")}

  enum status: {disable: 0, enable: 1}

  mount_uploader :image, ImageUploader
  validate :image_size
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :action_time

  PITCH_PARAMS = %i(description address image start_time end_time price status).freeze
  SELECT_HOME = %i(id description address image start_time end_time price status).freeze

  private

  def image_size
    return unless image.size > Settings.users.avatar_size.size.megabytes
    errors.add :image, I18n.t("error")
  end

  def action_time
    return unless start_time || end_time
    return if start_time < end_time
    errors.add :start_time, I18n.t(".error")
  end
end

app/controllers/owner/pitches_controller.rb
class Owner::PitchesController < OwnerController
  before_action :load_pitch, only: %i(edit update)
  before_action :correct_user, only: :destroy

  def index
    if params[:search]
      @pitches = current_user.pitches.create_at_desc.search_pitch(params[:search]).page(params[:page]).per Settings.perpage
    else
      @pitches = current_user.pitches.create_at_desc.page(params[:page]).per Settings.perpage
    end
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = current_user.pitches.build pitch_params

    if @pitch.save
      redirect_to owner_pitches_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @pitch.update_attributes pitch_params
      flash[:success] = t ".success"
      redirect_to owner_pitches_path
    else
      flash[:danger] =  t".not_update"
      render :edit
    end
  end

  def destroy
    @pitch.destroy

    if @pitch.destroyed?
      flash[:success] = t ".delete_pitch"
      redirect_to request.referrer || root_url
    else
      flash[:danger] =  t".not_deleted"
      redirect_to request.referrer || root_url
    end
  end

  private

  def pitch_params
    params.require(:pitch).permit Pitch::PITCH_PARAMS
  end

  def load_pitch
    @pitch = Pitch.find_by id: params[:id]

    return if @pitch
    flash[:danger] = t ".not_found"
    redirect_to owner_pitches_path
  end

  def correct_user
    @pitch = current_user.pitches.find_by id: params[:id]
    redirect_to owner_pitches_path unless @pitch
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def show
    @pitch = Pitch.find_by id: params[:id]
    @comment = Comment.new
    @comments = Comment.comment_desc.where(id: UserPitchReaction
      .where(reactions_type: Comment.name, pitch_id: params[:id]).pluck(:reactions_id))
      .page(params[:page]).per Settings.per_page_home

    return if @pitch
    flash[:danger] = t ".not_found"
    redirect_to root_url
  end
end

app/views/pitches/show.html.erb
<div class="container">
  <div class="card">
    <div class="container-fliud">
      <div class="wrapper row">
        <div class="preview col-md-6">
          <div class="preview-pic tab-content">
            <div class="tab-pane active">
              <%= get_image_pitch @pitch %>
            </div>
          </div>
        </div>
        <div class="details col-md-6">
          <h3 class="product-title"><%= @pitch.address %></h3>
            <div class="rating">
              <div class="stars">
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
              </div>
            <span class="review-no"><%= t ".number_reviews" %></span>
          </div>
            <p class="product-description"><%= @pitch.description %></p>
            <h4 class="price"><%= t ".current_price" %><span><%= @pitch.price %></span><%= t ".vnd" %></h4>
            <p><%= t ".time" %><%= @pitch.start_time.strftime(Settings.time.strftime) %>-<%= @pitch.end_time.strftime(Settings.time.strftime) %></p>
          <div class="action">
            <%= link_to t(".booking"), new_pitch_booking_path(@pitch), class: "add-to-cart btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
    <br>
    <section class="content-item" id="comments">
      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <% if current_user %>
              <%= render "comments/new" %>
            <% else %>
              <span><%= link_to "login", login_path %><%= t ".to_comment" %></span>
            <% end %>
            <div id="comment_partial">
              <% @comments.each do |comment| %>
                <%= render partial: "comments/comment", locals: {user: find_user_comment(comment), comment: comment} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class= "paginate">
        <%= paginate @comments, theme: Settings.theme %>
      </div>
    </section>
  </div>
</div>