config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"

  get "static_pages/home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: %i(index destroy)
  resources :change_date_booking, only: :show
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(new index create)
  
  resources :pitches do
    resources :bookings
  end

  namespace :owner do
    resources :pitches
  end
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  has_many :user_pitch_reactions, class_name: UserPitchReaction.name
  has_many :bookings, through: :user_pitch_reactions, source: :reactions,
    source_type: Booking.name, dependent: :destroy
  has_many :comments, through: :user_pitch_reactions, source: :reactions,
    source_type: Comment.name, dependent: :destroy

  scope :create_at_desc, -> {order created_at: :desc}
  scope :search_pitch, ->search{where("description LIKE ?", "%#{search}%").or where("address LIKE ?","%#{search}%")}

  enum status: {disable: 0, enable: 1}

  mount_uploader :image, ImageUploader
  validate :image_size
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :action_time

  PITCH_PARAMS = %i(description address image start_time end_time price status).freeze
  SELECT_HOME = %i(id description address image start_time end_time price status).freeze

  private

  def image_size
    return unless image.size > Settings.users.avatar_size.size.megabytes
    errors.add :image, I18n.t("error")
  end

  def action_time
    return unless start_time || end_time
    return if start_time < end_time
    errors.add :start_time, I18n.t(".error")
  end
end

app/controllers/owner/pitches_controller.rb
class Owner::PitchesController < OwnerController
  before_action :load_pitch, only: %i(edit update)
  before_action :correct_user, only: :destroy

  def index
    if params[:search]
      @pitches = current_user.pitches.create_at_desc.search_pitch(params[:search]).page(params[:page]).per Settings.perpage
    else
      @pitches = current_user.pitches.create_at_desc.page(params[:page]).per Settings.perpage
    end
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = current_user.pitches.build pitch_params

    if @pitch.save
      redirect_to owner_pitches_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @pitch.update_attributes pitch_params
      flash[:success] = t ".success"
      redirect_to owner_pitches_path
    else
      flash[:danger] =  t".not_update"
      render :edit
    end
  end

  def destroy
    @pitch.destroy

    if @pitch.destroyed?
      flash[:success] = t ".delete_pitch"
      redirect_to request.referrer || root_url
    else
      flash[:danger] =  t".not_deleted"
      redirect_to request.referrer || root_url
    end
  end

  private

  def pitch_params
    params.require(:pitch).permit Pitch::PITCH_PARAMS
  end

  def load_pitch
    @pitch = Pitch.find_by id: params[:id]

    return if @pitch
    flash[:danger] = t ".not_found"
    redirect_to owner_pitches_path
  end

  def correct_user
    @pitch = current_user.pitches.find_by id: params[:id]
    redirect_to owner_pitches_path unless @pitch
  end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  before_action :require_owner

  private

  def require_owner
    return if current_user.owner?
    flash[:danger] = t ".danger"
    redirect_to root_path
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  def show
    @pitch = Pitch.find_by id: params[:id]
    @comment = Comment.new
    @comments = Comment.comment_desc.where(id: UserPitchReaction
      .where(reactions_type: Comment.name, pitch_id: params[:id]).pluck(:reactions_id))
      .page(params[:page]).per Settings.per_page_home

    return if @pitch
    flash[:danger] = t ".not_found"
    redirect_to root_url
  end
end

app/views/owner/pitches/_form.html.erb
<%= form_for [:owner, @pitch] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label :description, t(".description") %>
  <%= f.text_field :description, class: "form-control", required: "required" %><br>
  <%= f.label :address, t(".address") %>
  <%= f.text_field :address, class: "form-control", required: "required" %><br>
  <%= f.label :image, t(".image") %>
  <%= f.file_field :image, class: "form-control" %><br>
  <%= f.label :start_time, t(".start_time") %>
  <%= f.time_field :start_time, class: "form-control", required: "required" %><br>
  <%= f.label :end_time, t(".end_time") %>
  <%= f.time_field :end_time, class: "form-control", required: "required" %><br>
  <%= f.label :price, t(".price") %>
  <%= f.number_field :price, class: "form-control", required: "required" %><br>
  <%= f.label :status, t(".status") %>
  <%= f.select :status, pitch_status_option, required: "required" %><br><br>
  <%= f.submit t(".submit"), class: "btn btn-primary" %>
<% end %>

app/views/owner/pitches/_pitch.html.erb
<tr>
  <td><%= pitch.description %></td>
  <td><%= pitch.address %></td>
  <td><%= get_image_pitch pitch %></td>
  <td><%= pitch.start_time %></td>
  <td><%= pitch.end_time %></td>
  <td><%= pitch.price %></td>
  <td><%= t(".owner.pitches.pitch.#{pitch.status}") %></td>
  <th><td><%= link_to t("update"), edit_owner_pitch_path(pitch), class: "btn btn-primary" %></td>
  <td><%= link_to t("delete"), owner_pitch_path(pitch), method: :delete, data: {confirm: t(".sure")}, class: "btn btn-danger" %></td></th>
</tr>

app/views/owner/pitches/edit.html.erb
<% provide :title, t(".update") %>
<h1><%= t ".update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/owner/pitches/index.html.erb
<% provide :title, t(".pitch") %>
<div class="container">
  <h2><%= t ".pitch" %></h2>
  <div>
    <%= form_tag(owner_pitches_path, class: "navbar-form navbar-right", method: :get) do |f| %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: t(".search") %>
          <div class="input-group-btn">
            <%= button_tag(type: "submit", class:"btn btn-default" ) do %>
              <i class="glyphicon glyphicon-search" id="icon_search"></i>
            <% end %>
          </div>
      </div>
    <% end %>
  </div>
  <%= link_to t(".add"), new_owner_pitch_path, class: "btn btn-info" %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t ".description" %></th>
        <th><%= t ".address" %></th>
        <th class="image_index"><%= t ".image" %></th>
        <th><%= t ".start_time" %></th>
        <th><%= t ".end_time" %></th>
        <th><%= t ".price" %></th>
        <th><%= t ".status" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @pitches %>
    </tbody>
  </table>
  <%= paginate @pitches, theme: Settings.theme %>
</div>

app/views/owner/pitches/new.html.erb
<% provide :title, t(".new") %>
<h1><%= t ".new" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>