config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#home"

  get "static_pages/home"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, except: %i(index destroy)
  resources :change_date_booking, only: :show
  resources :comments, only: %i(create destroy)
  resources :ratings, only: %i(new index create)
  
  resources :pitches do
    resources :bookings
  end

  namespace :owner do
    resources :pitches
  end
end

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h6><%= t ".about" %></h6>
        <p class="text-justify"><%= t ".justify" %></p>
      </div>
    </div><hr>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text"><%= t ".copyright" %></p>
      </div>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><a class="facebook"><i class="glyphicon glyphicon-flash"></i></a></li>
          <li><a class="twitter"><i class="glyphicon glyphicon-envelope"></i></a></li>
          <li><a class="dribbble"><i class="glyphicon glyphicon-thumbs-up"></i></a></li>
          <li><a class="linkedin"><i class="glyphicon glyphicon-shopping-cart"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    </div>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to t(".home"), root_path %></li>
    <li><%= link_to t(".sign_up"), signup_path %></li>
  <% if logged_in? %>
    <li class="dropdown">
    <%= link_to "#", :class => "dropdown-toggle", :data => { :toggle => "dropdown"} do %>
      <%= t ".account" %><b class="caret"></b>
    <% end %>
      <ul class="dropdown-menu">
        <li><%= link_to t(".profile"), current_user %></li>
        <li class="divider"></li>
        <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to t(".owner"), owner_pitches_path %></li>
        <li class="divider"></li>
        <li><%= link_to t(".log_out"), logout_path, method: :delete %></li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to t(".log_in"), login_path %></li>
  <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title yield :title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="content">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>